# Generated by Django 4.2.4 on 2023-08-09 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_api', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(related_name='news_feeds', to='blog_api.post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
