version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env 
    image: postgres:13  
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: hukumabob/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db          
  frontend:
    env_file: .env
    image: hukumabob/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    env_file: .env
    image: hukumabob/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/app/media/