version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env 
    image: postgres:13   
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    env_file: .env
    image: hukumabob/blog_backend
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
  gateway:
    env_file: .env
    image: hukumabob/blog_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
      - media:/app/media/     
